### ISSUE TITLE
Dragging in the middle of the screen does not work.

### ISSUE THREAD

**Issue by fyordan** [googleinterns/trace#116]
When moving around in the map, I cannot drag around when I click near the center of the screen. It looks like `<div class=mainButtonsWrapper>` is too tall, and prevents clicking the map underneath it.

Can it be made smaller?

**Comment by ccjeane** [comment]
Yes! I think this will be an easy fix with our UI overhaul.

**Comment by dterr** [comment]
Awesome. Thanks Fernando!!
