### ISSUE TITLE
Hide API KEY

### ISSUE THREAD

**Issue by kcirerick** [googleinterns/trace#28]
API Key should be removed form index.html into a config.js file which should be tracked in .gitignore

**Comment by kcirerick** [comment]
Rather than undergoing the arduous process of deleting the API Key from our commit history, i've decided to just make a new API Key and hide it from the start. This commit should be approved and merged asap since our old API key will no longer work.

**Comment by kcirerick** [comment]
Actually, with restricted API key access, our API key should be fine to stay visible since it can't be used with any external url anyways. However, if we wanted to open this site up to the public, this issue may become a higher priority.

**Comment by ccjeane** [comment]
Fixed
