### ISSUE TITLE
Populate Reviews page

### ISSUE THREAD

**Issue by kcirerick** [googleinterns/trace#29]
Once a user clicks on a search result, we should wipe the modal and populate it with a 'reviews' page which may contain:
-hours open
-total positive reviews
-total negative reviews
-actual reviews (and whether it's a positive or negative review based on our sentiment analysis ?)

**Comment by ccjeane** [comment]
Yes

**Comment by dterr** [comment]
Agreed

**Comment by ccjeane** [comment]
Done
