### ISSUE TITLE
Tutorial JS Implementation

### ISSUE THREAD

**Issue by dterr** [googleinterns/trace#58]
### Move HTML into JS Populator Function
We should try and review as much raw HTML into the index as possible, rather have a function that populates the tutorial into a hidden container on only the first visit to the website.

Lines 26-39 in index.html
```
<div id="tutorial-popup">
   <div id="header">
        <div id="exit">x</div>
          <p id="headerText">Welcome To TRACE</p>
      </div>
      <div id="lower">
        <div id="lowerCenter">
          <div id="centralDiv"> 
            <p id="centralText">Scroll through this tutorial to learn how to explore our site.</p>
          </div>
          <div class="float-container" id="navButtons">
            <a class="prev" onclick="">&#10094;</a>
            <a class="next" onclick="">&#10095;</a>
          </div>
        </div>
</div>
```
**Could be condensed into the following with JS populator function** 
```
<div id="tutorial-popup">
</div>
```

**Comment by kcirerick** [comment]
Would be easy in react, not worth the trouble in HTML/JS unless we have extra time towards the end. Gonna close for now.
