### ISSUE TITLE
Extend ReviewServlet to allow for collection of more information

### ISSUE THREAD

**Issue by kcirerick** [googleinterns/trace#59]
I could be wrong about this, but, right now, it seems that ReviewServlet retrieves all reviews on our site and just inserts new ones to the datastore without regard for the location it refers to or identifying information for the user who posted it. I think we should figure out how to collect multiple pieces of information for a single review including:
<ul>
<li>place_ID (location this review is about)</li>
<li>poster_ID (could be email or username of person who posted)</li>
<li>upvotes/downvotes</li>
<li> rating (out of 5 or 10 or whatever) </li>
<li>Actual review text</li>
<li>date/time</li>

**Comment by ccjeane** [comment]
It looks like you added some of this information in one of your last PR's, what else needs to be done?

**Comment by kcirerick** [comment]
Nothing, forgot to link PR, should be fine now.
